services:
  decluttarr:
    build:
      context: /home/josh/decluttarr/decluttarr
      dockerfile: docker/Dockerfile
    container_name: decluttarr
    restart: unless-stopped
    environment:
    - TZ=America/Detroit
    - PUID=1000
    - PGID=1000
    - LOG_LEVEL=VERBOSE
    - REMOVE_TIMER=15
    - REMOVE_FAILED=True
    - REMOVE_FAILED_IMPORTS=True
    - REMOVE_METADATA_MISSING=True
    - REMOVE_MISSING_FILES=True
    - REMOVE_ORPHANS=True
    - REMOVE_SLOW=False
    - REMOVE_STALLED=True
    - REMOVE_UNMONITORED=False
    - MIN_DOWNLOAD_SPEED=100
    - PERMITTED_ATTEMPTS=5
    - IGNORE_PRIVATE_TRACKERS=False
    - NO_STALLED_REMOVAL_QBIT_TAG=Don't Kill
    - RADARR_URL=http://192.168.1.4:7878
    - RADARR_KEY=7436ebfeffdc442592776acd19a22be2
    - SONARR_URL=http://192.168.1.4:8989
    - SONARR_KEY=dd2cf7bd8bf14843b5f3ea1ad1c68ad5
    networks:
    - decluttarr_network
  manager:
    build:
      context: .
      dockerfile_inline: 'FROM python:3.11-slim

        RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

        RUN pip install flask pyyaml requests

        WORKDIR /app

        COPY decluttarr-manager.py .

        EXPOSE 8081

        CMD ["python", "decluttarr-manager.py"]

        '
    container_name: decluttarr-manager
    restart: unless-stopped
    ports:
    - 8081:8081
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - .:/docker/decluttarr
    environment:
    - TZ=America/Detroit
    networks:
    - decluttarr_network
  log-viewer:
    image: amir20/dozzle:latest
    container_name: decluttarr-logs
    restart: unless-stopped
    ports:
    - 9999:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - DOZZLE_FILTER=name=decluttarr
    - DOZZLE_NO_ANALYTICS=true
    networks:
    - decluttarr_network
networks:
  decluttarr_network:
    driver: bridge
